# -*- coding: utf-8 -*-
"""Notes App V2.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vxb_tIddeXOac-2qC-JIdDCmCRgTKi2a
"""

notes = []   


try:
    with open('notes.txt', 'r') as f:
        notes = [line.strip() for line in f]
except FileNotFoundError:
    pass 


try:
    open('notes.txt', 'x').close()
except FileExistsError:
    pass

while True:
    print("\n--- Notes App ---")
    print("1. Add a note")
    print("2. Show all notes")
    print("3. Search notes")
    print("4. Delete a Note")
    print("5. Exit")

    choice = input("Choose an option (1-5): ").strip()

    if choice == "1":
        raw = input("Add your note (Optional: Category|Text):").strip()
   
        if not raw:
            print("Empty note not added.")
            continue
    

        cat = ""
        text = raw

        if "|" in raw:
            parts = raw.split("|", 1)
            cat = parts[0].strip()
            text = parts[1].strip()

            if not cat or not text:
                 print("Please, use 'Category|note' with both parts filled (e.g. Work|Finish report).")
                 continue
    
            stored = f"{cat}|{text}"
        else:
            stored = text

       
        def note_text_only(line):
          return line.split("|", 1)[-1].strip().lower()

        if any(note_text_only(stored) == note_text_only(n) for n in notes):
            print("Duplicate note not added.")
            continue

        
        notes.append(stored)
        with open('notes.txt', "a") as f:
            f.write(stored + "\n")
        print("Note added successfully!")

    elif choice == "2":
        try:
            with open('notes.txt', 'r') as f:
                notes = [line.strip() for line in f]
        except FileNotFoundError:
            notes = []

        if not notes:
            print("No notes yet. Add one with option 1.")
        else:
            print("\n--- Notes ---")
            for i, note in enumerate(notes, start=1):
              if "|" in note:
                cat, text = note.split("|", 1)
                print(f"{i}.[{cat.strip()}] {text.strip()}")
              else:
                print(f"{i}. {note}")

    elif choice == "3":
        term = input("Search for:").strip().lower()

        if not term:
            print("Empty search term. Try again.")
            continue

        try:
            with open('notes.txt', 'r') as f:
                notes = f.read().splitlines()
        except FileNotFoundError:
            notes = []

        matches = []
        for i, note in enumerate(notes, start=1):
            if term in note.lower():
                matches.append((i, note))

        if matches:
            print("\nMatches:")
            for idx, text in matches:
              if "|" in note:
                cat, text = text.split("|", 1)
                print(f"{idx}. [{cat.strip()}] {text.strip()}")
              else:
                print(f"{idx}. {note}")
        else:
            print("No matches found.")

    elif choice == "4":
        try:
            with open('notes.txt', 'r') as f:
                notes = [line.strip() for line in f]
        except FileNotFoundError:
            notes = []

        if not notes:
            print("No notes to delete.")
            continue

        print("\n--- Notes ---")
        for i, note in enumerate(notes, start=1):
            print(f"{i}. {note}")

        idx_str = input(f"Delete which number? (1-{len(notes)}): ").strip()
        if not idx_str.isdigit():
               print("Invalid input. Please enter a number.")
               continue

        idx = int(idx_str)
        if not (1 <= idx <= len(notes)):
               print("Invalid note number.")
               continue

        ans = input(f"Are you sure you want to delete note {idx}? (y/n): ").strip().lower()
        if not ans.startswith("y"):
            print("Deletion cancelled.")
            continue

        deleted_note = notes.pop(idx - 1)
        with open("notes.txt","w") as f:
          for n in notes:
            f.write(n + "\n")

        print(f"Note '{deleted_note}' deleted successfully!")

    elif choice == "5":
        print("Goodbye!")
        break
    else:
        print("Invalid choice, try again.")

